name: Bug
on:
  issue_comment:
    types: [ created ]    
jobs:
  test:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Get content of file
        uses: actions/github-script@v6.0.0
        with:
          debug: true
          script: |
            let data = await github.rest.repos.getContent({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              path: 'test.json',
              mediaType: {
                format: "raw"
              }
            })
            console.log(data)